import "./Headers&Footers.scss"
import "../../block/header1/header1"
import "../../block/footer1/footer1"
import "../../block/footer2/footer2"
import "../../block/social-network-icons/social-network-icons"